export const products = [
  {
    id: 4,
    name: 'AURA TEE',
    price: 899,
    description: 'Nuestra Aura Tee destaca por su diseño minimalista y corte premium. Una pieza esencial que eleva cualquier conjunto.',
    images: ['/images/remeraNegraModelo.png', '/images/remeraNegraModeloFrente.png', '/images/remeraNegraFrente.jpeg', '/images/remeraNegraMovimiento.jpeg', '/images/remeraNegraTren.jpeg'],
    sizes: ['S', 'M', 'L'],
    colors: ['Crema'],
    inStock: true,
  },
  
  {
    id: 5,
    name: 'NEVER QUIT BORDO',
    price: 899,
    description: 'Nuestra Aura Tee destaca por su diseño minimalista y corte premium. Una pieza esencial que eleva cualquier conjunto.',
    images: ['/images/neverQuitBlackMen.jpeg', '/images/NeverQuitMujerEspalda.jpeg', '/images/neverQuitBordo.jpeg','/images/neverQuitBordoFrente.jpeg','/images/neverQuitBordoReja.jpeg'],
    sizes: ['S', 'M', 'L'],
    colors: ['Crema'],
    inStock: true,
  },
  {
    id: 1,
    name: 'RENAISSANCE TEE',
    price: 799,
    description: 'Nuestra remera Renaissance captura la esencia del arte clásico en un formato moderno. Confeccionada con algodón de alta calidad para máxima comodidad.',
    images: [ '/images/remeraReinModeloEspalda.PNG', '/images/remeraReinModeloFrente.jpeg', '/images/ReinMujerEspalda.jpeg','/images/angelEspalda.jpeg', '/images/remeraReinCollage.jpeg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blanco', 'Negro'],
    inStock: true,
  },
  {
    id: 6,
    name: 'Remera de TINI',
    price: 799,
    description: 'Remera de Tini para el concierto el 22 de febrero.',
    images: ['/images/tiniModelo.jpg.jpeg', '/images/tini.png' ],
    sizes: ['S', 'M', 'L'],
    colors: ['Crema'],
    inStock: true,
  },
  {
    id: 2,
    name: 'NEVER QUIT AZUL',
    price: 859,
    description: 'La determinación hecha prenda. La remera Never Quit en color azul es ideal para tus entrenamientos o para un look casual con actitud.',
    images: ['/images/neverQuitAzul.jpeg', '/images/neverQuitAzulAtras.jpeg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Azul'],
    inStock: false,
  },
  {
    id: 3,
    name: 'NEVER QUIT MARRÓN',
    price: 859,
    description: 'Versatilidad y estilo en uno. El color marrón tierra de nuestra línea Never Quit ofrece una alternativa sofisticada para tu día a día.',
    images: ['/images/NeverQuitMarron.jpeg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Marrón'],
    inStock: false,
  },
];

export const WHATSAPP_PHONE = '+59892550478'; // Example phone number

